application: co-labs
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /s
  static_dir: s

- url: /login
  script: main.app
  secure: always

- url: /forgot
  script: main.app
  secure: always

- url: .*
  script: main.app

builtins:
- remote_api: on

libraries:
- name: jinja2
  version: latest
- name: webapp2
  version: "2.5.2"
